### ISSUE TITLE
Support JDK 20?

### ISSUE THREAD

**Issue by ajaxsys** [sourcebuddy/sourcebuddy#3]
As OpenJDK JDK 20 General-Availability released, consider upgrading to the supported JDK 20?

**Comment by verhas** [comment]
Yes, of course. It was released yesterday as GA.

It is important that I get feedback like this so that I know that people are using my tool.

While I may attend to it, please elaborate on what new features you envision. Did you try to use SourceBuddy with Java 20, and it did not work? What specific changes would you like to see in the next release?

**Comment by ajaxsys** [comment]
Yes! we love your tools, we are using it for dynamic generate java source code while ER modeling.

>  Did you try to use SourceBuddy with Java 20, and it did not work? 
We tried it with Java 20 and got error that had been mentioned in readme.md :

```
Caused by: java.lang.RuntimeException: This version support Java up to version 19.
	at com.javax0.sourcebuddy.NameGouger.getBinaryName(NameGouger.java:29)
	at com.javax0.sourcebuddy.Compiler.getBinaryName(Compiler.java:625)
	at com.javax0.sourcebuddy.Compiler.lambda$saveTo$2(Compiler.java:608)
	... 35 more
```

**Comment by verhas** [comment]
Yes, you are right. I am currently buried in implementing OpenAI module for Jamal, and my brain is deep into that, so I forgot that the feature that reads the byte code limits itself to the known versions.

I do not know of any changes in the JVM byte code format from 19 to 20, but it has to be checked, and then bumping the constants in the source code is the only fix needed.

I will not have time to do the research this week, though.

If you feel like it, you can do the research and create a pull request.  I bumped up branch main to 2.2.1-SNAPSHOT, so you can fork, and don't forget to add a credit line with your references to the RELEASES.adoc.jam file.

**Comment by ajaxsys** [comment]
Thanks for your commit, I am not so clear about Java byte code, but I will try to do a research.

**Comment by ajaxsys** [comment]
> I do not know of any changes in the JVM byte code format from 19 to 20, but it has to be checked

I tried upgrade [JVM_VERSION](https://github.com/sourcebuddy/sourcebuddy/blob/main/src/main/java/com/javax0/sourcebuddy/ByteCodeGouger.java#L9) to `64` (JDK 20) , and seams no problems in our codebase. 

I will continue to do more tests.

**Comment by verhas** [comment]
The release 2.3.0 should solve this issue.
